"use strict";

exports.__esModule = true;

var _FLAG_DEFAULTS;

var BATCHES_ESCHEATMENTS = exports.BATCHES_ESCHEATMENTS = "batches-escheatments";
var DISBURSEMENTS_CREDIT_CARDS = exports.DISBURSEMENTS_CREDIT_CARDS = "disbursements-credit-cards";
var QANDP_POLICY_VITALS = exports.QANDP_POLICY_VITALS = "qandp-policy-vitals";
var REFERRALS_PIC_FILTER = exports.REFERRALS_PIC_FILTER = "referrals-pic-filter";
var REFERRALS_LEGACY_LINK = exports.REFERRALS_LEGACY_LINK = "referrals-legacy-linking";
var QANDP_ACCOUNTING_FORMS = exports.QANDP_ACCOUNTING_FORMS = "q-p-accounting-forms";
var QANDP_POLICY_MANAGER_FORMS = exports.QANDP_POLICY_MANAGER_FORMS = "q-p-policy-manager-forms";
var QANDP_PRINT_AND_MAIL_DOCUMENTS = exports.QANDP_PRINT_AND_MAIL_DOCUMENTS = "q-p-print-and-mail-documents";
var QANDP_SAVE_ACH_INFO = exports.QANDP_SAVE_ACH_INFO = "q-p-save-ach-info";
var QANDP_EASYPAY_INFO = exports.QANDP_EASYPAY_INFO = "q-p-easy-pay-account-information";
var QANDP_ANALYSIS = exports.QANDP_ANALYSIS = "q-p-analysis";
var QANDP_RENEWAL_UNDERWRITING = exports.QANDP_RENEWAL_UNDERWRITING = "q-p-renewal-underwriting";
var QANDP_UNDERWRITING_REFERRALS = exports.QANDP_UNDERWRITING_REFERRALS = "q-p-underwriting-referrals";
var QANDP_VIEW_ADVANCED = exports.QANDP_VIEW_ADVANCED = "q-p-view-advanced";
var QANDP_POLICY_INSPECTIONS = exports.QANDP_POLICY_INSPECTIONS = "q-p-policy-inspections";
var QANDP_LEGACY_VIEW = exports.QANDP_LEGACY_VIEW = "q-p-legacy-view";
var QANDP_SERVICE_REQUESTS_DEMO = exports.QANDP_SERVICE_REQUESTS_DEMO = "q-p-service-requests-demo";

var FLAG_DEFAULTS = exports.FLAG_DEFAULTS = (_FLAG_DEFAULTS = {}, _FLAG_DEFAULTS[BATCHES_ESCHEATMENTS] = false, _FLAG_DEFAULTS[DISBURSEMENTS_CREDIT_CARDS] = false, _FLAG_DEFAULTS[QANDP_POLICY_VITALS] = false, _FLAG_DEFAULTS[REFERRALS_LEGACY_LINK] = false, _FLAG_DEFAULTS[REFERRALS_PIC_FILTER] = true, _FLAG_DEFAULTS[QANDP_ACCOUNTING_FORMS] = false, _FLAG_DEFAULTS[QANDP_POLICY_MANAGER_FORMS] = false, _FLAG_DEFAULTS[QANDP_PRINT_AND_MAIL_DOCUMENTS] = false, _FLAG_DEFAULTS[QANDP_SAVE_ACH_INFO] = false, _FLAG_DEFAULTS[QANDP_EASYPAY_INFO] = false, _FLAG_DEFAULTS[QANDP_ANALYSIS] = false, _FLAG_DEFAULTS[QANDP_RENEWAL_UNDERWRITING] = false, _FLAG_DEFAULTS[QANDP_UNDERWRITING_REFERRALS] = false, _FLAG_DEFAULTS[QANDP_VIEW_ADVANCED] = false, _FLAG_DEFAULTS[QANDP_POLICY_INSPECTIONS] = false, _FLAG_DEFAULTS[QANDP_LEGACY_VIEW] = false, _FLAG_DEFAULTS[QANDP_SERVICE_REQUESTS_DEMO] = false, _FLAG_DEFAULTS);